Final_pjt/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('compare/', views.compare_products, name='compare_products'),
]

Final_pjt/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path(
        '<int:article_pk>/comments/<int:comment_pk>/delete/',
        views.comments_delete,
        name='comments_delete',
    ),
    path('<int:article_pk>/likes/', views.likes, name='likes'),
    path('<int:article_pk>/comments/<int:comment_pk>/update/', views.comments_update, name='comments_update')
]

# urlpatterns = [
#     path('articles/', views.article_list),
#     path('articles/<int:article_pk>/', views.article_detail),
# ]

Final_pjt/final_pjt_back/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views
from django.views.generic import RedirectView
# from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', TemplateView.as_view(template_name='base.html'), name='home'),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('finlife/', include('finlife.urls')),
    path('articles/', include('articles.urls')),
    path('myapp/', include('myapp.urls')),
    path('survey/', include('survey.urls')),
    path('exchange_app/', include('exchange_app.urls')),
    path('', RedirectView.as_view(url='/mainpage/', permanent=False)),  # 루트 URL 리디렉션
    path('mainpage/', include('mainpage.urls')),  # 메인 페이지를 제공하는 앱의 URL 설정을 포함
    # path('<int:user_pk>/password/', views.change_password, name='change_password')
]

Final_pjt/finlife/urls.py
from django.urls import path
from . import views

app_name = "finlife"
urlpatterns = [
    path('', views.index, name="index"),
    path('filter/', views.filter, name="filter"),
    path('compare/', views.compare_products, name='compare'),
    path('<str:product_type>/<int:product_id>/', views.product_detail, name='product_detail'),
    path('enroll/<str:product_type>/<int:product_id>/', views.enroll_product, name='enroll_product'),
]

Final_pjt/myapp/urls.py
# myapp/urls.py

from django.urls import path
from . import views

app_name ='myapp'
urlpatterns = [
    path('map/', views.map_view, name='map'),  # 빈 문자열로 설정하여 기본 경로로 매핑
]

Final_pjt/survey/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView
from django.views.generic import TemplateView

app_name ='survey'
urlpatterns = [
    path('', views.index, name='index'),
    path('recommendations/', views.recommend_products, name='recommendations'),
]

Final_pjt/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from finlife.models import DepositProducts, SavingProducts

# Create your models here.

class User(AbstractUser):
    address = models.TextField(blank=True, null=True, verbose_name="주소")
    birthday = models.DateTimeField(blank=True, null=True, verbose_name="생년월일")
    assets = models.IntegerField(blank=True, null=True, verbose_name="자산")
    Goal = models.IntegerField(blank=True, null=True, verbose_name="목표")
    enrolled_deposit_products = models.ManyToManyField(DepositProducts, blank=True, related_name='enrolled_users')
    enrolled_saving_products = models.ManyToManyField(SavingProducts, blank=True, related_name='enrolled_users')

Final_pjt/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import User
from django import forms

# class CustomUserCreationForm(UserCreationForm):
#     class Meta(UserCreationForm.Meta):
#         model = get_user_model()
        
class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'password1', 'password2', 'address', 'birthday', 'assets', 'Goal')
        labels = {
            'username': '닉네임',
            'password1': '비밀번호',
            'password2': '비밀번호 확인',
            'address': '주소',
            'birthday': '생년월일',
            'assets': '자산',
            'Goal': '목표'
        }
        help_texts = {
            'username': '',
            'password1': '',
            'password2': '',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].help_text = None
        self.fields['password2'].help_text = None
        self.fields['birthday'].widget = forms.DateInput(attrs={'type': 'date'})


class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = (
            'username', 
            'address',
            'birthday',
            'assets',
            'Goal',
        )
        labels = {
            'username': '닉네임',
        }
        help_texts = {
            'username': '',
        }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['birthday'].widget = forms.DateInput(attrs={'type': 'date'})
        # 비밀번호 필드 제거
        if 'password' in self.fields:
            del self.fields['password']

Final_pjt/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import get_user_model
from .forms import CustomUserChangeForm, CustomUserCreationForm
from finlife.models import DepositProducts, SavingProducts

# from .forms import UserForm


# Create your views here.
def login(request):
    if request.user.is_authenticated:
        return redirect('mainpage:mainpage')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('mainpage:mainpage')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@login_required
def logout(request):
    auth_logout(request)
    return redirect('mainpage:mainpage')


def signup(request):
    if request.user.is_authenticated:
        return redirect('mainpage:mainpage')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('mainpage:mainpage')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


@login_required
def delete(request):
    request.user.delete()
    return redirect('mainpage:mainpage')


@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('mainpage:mainpage')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
        # 'user_pk': request.user.pk,  # 현재 로그인된 사용자의 pk를 컨텍스트에 추가
    }
    return render(request, 'accounts/update.html', context)


@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('mainpage:mainpage')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/change_password.html', context)


@login_required
def profile(request, username):
    User = get_user_model()
    person = get_object_or_404(User, username=username)
    enrolled_deposit_products = person.enrolled_deposit_products.all()
    enrolled_saving_products = person.enrolled_saving_products.all()
    
    context = {
        'person': person,
        'enrolled_deposit_products': enrolled_deposit_products,
        'enrolled_saving_products': enrolled_saving_products,
    }
    return render(request, 'accounts/profile.html', context)

@login_required
def compare_products(request):
    deposit_product_ids = request.POST.getlist('deposit_products')
    saving_product_ids = request.POST.getlist('saving_products')

    deposit_products = DepositProducts.objects.filter(id__in=deposit_product_ids)
    saving_products = SavingProducts.objects.filter(id__in=saving_product_ids)

    context = {
        'deposit_products': deposit_products,
        'saving_products': saving_products,
    }
    return render(request, 'accounts/compare.html', context)

Final_pjt/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}
  <h1>비밀번호 변경</h1>
  {% comment %} <form action="{% url "change_password" user.pk %}" method="POST"> {% endcomment %}
  <form action="{% url 'accounts:change_password' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
{% endblock content %}

Final_pjt/accounts/templates/accounts/compare.html
{% extends "base.html" %}

{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'finlife.css' %}">
{% endblock style %}

{% block content %}
<div class="container">
    <h1>비교 결과</h1>

    <h2>예금 상품</h2>
    <div class="table-container">
        <table class="table">
            <thead>
                <tr>
                    <th>금융 회사명</th>
                    <th>상품명</th>
                    <th>기타 유의사항</th>
                    <th>최고 한도</th>
                    <th>금리</th>
                    <th>우대 금리</th>
                    <th>저축 기간</th>
                </tr>
            </thead>
            <tbody>
                {% for product in deposit_products %}
                <tr>
                    <td>{{ product.kor_co_nm }}</td>
                    <td>{{ product.fin_prdt_nm }}</td>
                    <td>{{ product.etc_note }}</td>
                    <td>{{ product.max_limit }}</td>
                    <td>
                        {% for option in product.options.all %}
                            <div>{{ option.intr_rate }}%</div>
                        {% endfor %}
                    </td>
                    <td>
                        {% for option in product.options.all %}
                            <div>{{ option.intr_rate2 }}%</div>
                        {% endfor %}
                    </td>
                    <td>
                        {% for option in product.options.all %}
                            <div>{{ option.save_trm }}개월</div>
                        {% endfor %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <h2>적금 상품</h2>
    <div class="table-container">
        <table class="table">
            <thead>
                <tr>
                    <th>금융 회사명</th>
                    <th>상품명</th>
                    <th>기타 유의사항</th>
                    <th>최고 한도</th>
                    <th>금리</th>
                    <th>우대 금리</th>
                    <th>적립 유형명</th>
                    <th>저축 기간</th>
                </tr>
            </thead>
            <tbody>
                {% for product in saving_products %}
                <tr>
                    <td>{{ product.kor_co_nm }}</td>
                    <td>{{ product.fin_prdt_nm }}</td>
                    <td>{{ product.etc_note }}</td>
                    <td>{{ product.max_limit }}</td>
                    <td>
                        {% for option in product.options.all %}
                            <div>{{ option.intr_rate }}%</div>
                        {% endfor %}
                    </td>
                    <td>
                        {% for option in product.options.all %}
                            <div>{{ option.intr_rate2 }}%</div>
                        {% endfor %}
                    </td>
                    <td>
                        {% for option in product.options.all %}
                            <div>{{ option.rsrv_type_nm }}</div>
                        {% endfor %}
                    </td>
                    <td>
                        {% for option in product.options.all %}
                            <div>{{ option.save_trm }}개월</div>
                        {% endfor %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <a href="{% url 'accounts:profile' user.username %}">뒤로 가기</a>
</div>
{% endblock content %}

Final_pjt/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% load static %}
{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'accounts.css' %}">
{% endblock %}

{% block content %}
<div class="main-container">
  <div class="container login-container">
    <h1>Login</h1>
    <form action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="로그인">
    </form>
  </div>
</div>
{% endblock %}

Final_pjt/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% load humanize %}
{% load static %}
{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'accounts.css' %}">
{% endblock %}

{% block content %}
<div class="main-container">
  <div class="container profile-container">
    <h1>{{ person.username }}님의 프로필 페이지</h1>
    <div class="profile-info">
        <p>이름: {{ person.username }}</p>
        <p>주소: {{ person.address }}</p>
        <p>생일: {{ person.birthday|date:"Y-m-d" }}</p>
        <p>보유자산: {{ person.assets|intcomma }}원</p>
        <p>목표금액: {{ person.Goal|intcomma }}원</p>
        <a href="{% url 'accounts:update' %}">회원정보 수정하기</a>
    </div>
    <hr>
    <form method="post" action="{% url 'accounts:compare_products' %}">
        {% csrf_token %}
        <h3>가입한 예금 상품</h3>
        <ul class="product-list">
            {% for product in enrolled_deposit_products %}
            <li>
                <input type="checkbox" name="deposit_products" value="{{ product.id }}">
                <a href="{% url 'finlife:product_detail' 'deposit' product.id %}">{{ product.kor_co_nm }} - {{ product.fin_prdt_nm }}</a>
            </li>
            {% endfor %}
        </ul>
        
        <h3>가입한 적금 상품</h3>
        <ul class="product-list">
            {% for product in enrolled_saving_products %}
            <li>
                <input type="checkbox" name="saving_products" value="{{ product.id }}">
                <a href="{% url 'finlife:product_detail' 'saving' product.id %}">{{ product.kor_co_nm }} - {{ product.fin_prdt_nm }}</a>
            </li>
            {% endfor %}
        </ul>
        <br>
        <button type="submit" class="compare-button">비교하기</button>
    </form>
    <div class="link-container">
        <a href="{% url 'survey:recommendations' %}" class="custom-link">금융 상품 추천받기</a> 
        <a href="{% url 'articles:index' %}" class="custom-link">되돌아가기</a>
    </div>
  </div>
</div>
{% endblock %}

Final_pjt/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% load static %}
{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'accounts.css' %}">
{% endblock %}

{% block content %}
<div class="main-container">
  <div class="container signup-container">
    <h2>회원가입</h2>
    <form action="{% url 'accounts:signup' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="회원가입">
    </form>
    <a href="{% url 'articles:index' %}">메인으로</a>
  </div>
</div>
{% endblock %}

Final_pjt/accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% load static %}
{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'accounts.css' %}">
{% endblock %}

{% block content %}
<div class="main-container">
  <div class="container update-container">
    <h2>회원정보 수정</h2>
    <form action="{% url 'accounts:update' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <div>
            <a href="{% url 'accounts:change_password' %}">비밀번호 수정하기</a>
        </div>
        <input type="submit" value="수정하기">
    </form>
  </div>
</div>
{% endblock %}