Final_pjt/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path(
        '<int:article_pk>/comments/<int:comment_pk>/delete/',
        views.comments_delete,
        name='comments_delete',
    ),
    path('<int:article_pk>/likes/', views.likes, name='likes'),
    path('<int:article_pk>/comments/<int:comment_pk>/update/', views.comments_update, name='comments_update')
]

# urlpatterns = [
#     path('articles/', views.article_list),
#     path('articles/<int:article_pk>/', views.article_detail),
# ]

Final_pjt/final_pjt_back/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views
from django.views.generic import RedirectView
# from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', TemplateView.as_view(template_name='base.html'), name='home'),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('finlife/', include('finlife.urls')),
    path('articles/', include('articles.urls')),
    path('myapp/', include('myapp.urls')),
    path('survey/', include('survey.urls')),
    path('exchange_app/', include('exchange_app.urls')),
    path('', RedirectView.as_view(url='/mainpage/', permanent=False)),  # 루트 URL 리디렉션
    path('mainpage/', include('mainpage.urls')),  # 메인 페이지를 제공하는 앱의 URL 설정을 포함
    # path('<int:user_pk>/password/', views.change_password, name='change_password')
]

Final_pjt/myapp/urls.py
# myapp/urls.py

from django.urls import path
from . import views

app_name ='myapp'
urlpatterns = [
    path('map/', views.map_view, name='map'),  # 빈 문자열로 설정하여 기본 경로로 매핑
]

Final_pjt/articles/models.py
from django.db import models
from django.conf import settings

# django에서는 User 모델을 '직접' 참조하지 않는다.
# from accounts.models import User


# Create your models here.
class Article(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='like_articles'
    )
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

Final_pjt/articles/forms.py
from django import forms
from .models import Article, Comment


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('title', 'content',)
        labels = {
            'title': '제목',
            'content': '내용',
        }
        widgets = {
            'title': forms.TextInput(attrs={
                'placeholder': '제목을 입력하세요',
                'required': True,
            }),
            'content': forms.Textarea(attrs={
                'placeholder': '내용을 입력하세요',
                'required': True,
            }),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

Final_pjt/articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from .models import Article, Comment
from .forms import ArticleForm, CommentForm
from django.core.paginator import Paginator


# Create your views here.
def index(request):
    articles = Article.objects.all().order_by('created_at')  # 오름차순으로 정렬
    paginator = Paginator(articles, 10)  # 한 페이지에 10개의 게시글

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    # 페이지네이션을 역순으로 처리
    # page_obj.object_list = list(page_obj.object_list)[::-1]

    context = {
        'page_obj': page_obj,
    }
    return render(request, 'articles/index.html', context)

    

def detail(request, pk):
    article = Article.objects.get(pk=pk)
    comments = article.comment_set.all()
    comment_form = CommentForm()
    context = {
        'article': article,
        'comments': comments,
        'comment_form': comment_form,
    }
    return render(request, 'articles/detail.html', context)


@login_required
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm()
    context = {
        'form': form,
    }
    return render(request, 'articles/create.html', context)


@login_required
def delete(request, pk):
    article = Article.objects.get(pk=pk)
    if request.user == article.user:
        article.delete()
    return redirect('articles:index')


@login_required
def update(request, pk):
    article = Article.objects.get(pk=pk)
    if request.user == article.user:
        if request.method == 'POST':
            form = ArticleForm(request.POST, instance=article)
            if form.is_valid():
                form.save()
                return redirect('articles:detail', article.pk)
        else:
            form = ArticleForm(instance=article)
    else:
        return redirect('articles:index')
    context = {
        'form': form,
        'article': article,
    }
    return render(request, 'articles/update.html', context)


@login_required
def comments_create(request, pk):
    article = Article.objects.get(pk=pk)
    comments = article.comment_set.all()
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.article = article
        comment.user = request.user
        comment.save()
        return redirect('articles:detail', article.pk)
    context = {
        'comment_form': comment_form,
        'article': article,
        'comments': comments,
    }
    return render(request, 'articles/detail.html', context)


@login_required
def comments_delete(request, article_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.user == comment.user:
        comment.delete()
    return redirect('articles:detail', article_pk)

@login_required
def comments_update(request, article_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    if request.user != comment.user:
        return redirect('articles:detail', article_pk)

    if request.method == "POST":
        comment_form = CommentForm(request.POST, instance=comment)
        if comment_form.is_valid():
            comment_form.save()
            return redirect('articles:detail', article_pk)
    else:
        comment_form = CommentForm(instance=comment)

    context = {
        'comment_form': comment_form,
        'article': comment.article,
        'comment': comment,
    }
    return render(request, 'articles/comment_update.html', context)

@login_required
def likes(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    if request.user in article.like_users.all():
        article.like_users.remove(request.user)
        is_liked = False
    else:
        article.like_users.add(request.user)
        is_liked = True
    context = {
        'is_liked': is_liked,
        'liked_count': article.like_users.count(),
    }
    # return JsonResponse(context)
    return redirect('articles:index')

Final_pjt/articles/templates/articles/comment_update.html
{% extends 'base.html' %}

{% block style %}
{% load static %}
<link rel="stylesheet" href="{% static 'articles.css' %}">
{% endblock style %}

{% block content %}
<div class="container">
    <h2>댓글 수정</h2>
    <form action="{% url 'articles:comments_update' article.pk comment.pk %}" method="POST">
        {% csrf_token %}
        {{ comment_form.as_p }}
        <input type="submit" value="수정하기">
        <a class="input_link" href="{% url 'articles:detail' article.pk %}">취소</a>
    </form>
</div>
{% endblock content %}

Final_pjt/articles/templates/articles/create.html
{% extends 'base.html' %}

{% block style %}
{% load static %}
<link rel="stylesheet" href="{% static 'articles.css' %}">
{% endblock style %}

{% block content %}
<div class="container">
    <h2>글쓰기</h2>
    <form action="{% url 'articles:create' %}" method="POST">
        {% csrf_token %}
        <label for="{{ form.title.id_for_label }}">제목:</label>
        {{ form.title }}
        {{ form.title.errors }}

        <label for="{{ form.content.id_for_label }}">내용:</label>
        {{ form.content }}
        {{ form.content.errors }}

        <input type="submit" value="등록">
        <button id="cancelButton">뒤로가기</button>
    </form>
</div>

<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>
    document.getElementById("cancelButton").addEventListener("click", function(event) {
        event.preventDefault(); // 기본 제출 동작을 막음
        window.location.href = "{% url 'articles:index' %}"; // 원하는 URL로 이동
    });
</script>
{% endblock content %}

Final_pjt/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block style %}
{% load static %}
<link rel="stylesheet" href="{% static 'articles.css' %}">
{% endblock style %}

{% block content %}
<div class="container">
    <h1>Detail</h1>
    <h2>{{ article.pk }} 번째 글</h2>
    <hr>
    <p>작성자: {{ article.user }}</p>
    <p>제목: {{ article.title }}</p>
    <p>내용: {{ article.content }}</p>
    <p>작성일: {{ article.created_at }}</p>
    <p>수정일: {{ article.updated_at }}</p>
    <hr>
    {% if request.user == article.user %}
    <a href="{% url 'articles:update' article.pk %}">UPDATE</a>
    <form action="{% url 'articles:delete' article.pk %}" method="POST" style="display: inline;">
        {% csrf_token %}
        <input type="submit" value="DELETE">
    </form>
    <hr>
    {% endif %}
    <h3>댓글 작성</h3>
    <form action="{% url 'articles:comments_create' article.pk %}" method="POST">
        {% csrf_token %}
        {{ comment_form }}
        <input type="submit" value="댓글 작성">
    </form>
    <hr>
    <h3>댓글 목록</h3>
    <ul>
        {% for comment in comments %}
        <li>
            {{ comment.user }} - {{ comment.content }}
            {% if request.user == comment.user %}
            <a class="input_link" href="{% url 'articles:comments_update' article.pk comment.pk %}">수정</a>
            <form action="{% url 'articles:comments_delete' article.pk comment.pk %}" method="POST" style="display: inline;">
                {% csrf_token %}
                <input type="submit" value="삭제">
            </form>
            {% endif %}
        </li>
        <br>
        {% endfor %}
    </ul>
    <hr>
    <a href="{% url 'articles:index' %}">[back]</a>
</div>
{% endblock content %}

Final_pjt/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block style %}
{% load static %}
<link rel="stylesheet" href="{% static 'articles.css' %}">
{% endblock style %}

{% block content %}
<div class="container table-container">
    <h2>게시판</h2>
    <table class="table" id="postsTable">
        <tr class="header">
            <th class="num">번호</th>
            <th class="title">제목</th>
            <th class="author">작성자</th>
            <th class="date">등록일</th>
        </tr>
        {% for article in page_obj %}
        <tr class="body">
            <td class="num">{{ article.pk }}</td>
            <td class="title">
                <a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a>
            </td>
            <td class="author">{{ article.user }}</td>
            <td class="date">{{ article.created_at|date:"Y-m-d" }}</td>
        </tr>
        {% endfor %}
    </table>

    <div class="pagination">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; 처음</a>
            <a href="?page={{ page_obj.previous_page_number }}">&lsaquo; 이전</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <span class="current">{{ num }}</span>
            {% elif num > page_obj.number|add:'-5' and num < page_obj.number|add:'5' %}
                <a href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">다음 &rsaquo;</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">끝 &raquo;</a>
        {% endif %}
    </div>

    <button onclick="redirectToIndex()">글 작성하기</button>
</div>

<script>
    function redirectToIndex() {
        window.location.href = "{% url 'articles:create' %}";
    }
</script>
{% endblock content %}

Final_pjt/articles/templates/articles/update.html
{% extends 'base.html' %}

{% block style %}
{% load static %}
<link rel="stylesheet" href="{% static 'articles.css' %}">
{% endblock style %}

{% block content %}
<div class="container">
    <h2>수정하기</h2>
    <form action="{% url 'articles:update' article.pk %}" method="POST">
        {% csrf_token %}
        <label for="{{ form.title.id_for_label }}">제목:</label>
        {{ form.title }}
        {{ form.title.errors }}

        <label for="{{ form.content.id_for_label }}">내용:</label>
        {{ form.content }}
        {{ form.content.errors }}

        <input type="submit" value="등록">
        <button id="cancelButton">뒤로가기</button>
    </form>
</div>

<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>
    document.getElementById("cancelButton").addEventListener("click", function(event) {
        event.preventDefault(); // 기본 제출 동작을 막음
        window.location.href = "{% url 'articles:index' %}"; // 원하는 URL로 이동
    });
</script>
{% endblock content %}