Final_pjt/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('compare/', views.compare_products, name='compare_products'),
]

Final_pjt/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path(
        '<int:article_pk>/comments/<int:comment_pk>/delete/',
        views.comments_delete,
        name='comments_delete',
    ),
    path('<int:article_pk>/likes/', views.likes, name='likes'),
    path('<int:article_pk>/comments/<int:comment_pk>/update/', views.comments_update, name='comments_update')
]

# urlpatterns = [
#     path('articles/', views.article_list),
#     path('articles/<int:article_pk>/', views.article_detail),
# ]

Final_pjt/final_pjt_back/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views
from django.views.generic import RedirectView
# from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', TemplateView.as_view(template_name='base.html'), name='home'),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('finlife/', include('finlife.urls')),
    path('articles/', include('articles.urls')),
    path('myapp/', include('myapp.urls')),
    path('survey/', include('survey.urls')),
    path('exchange_app/', include('exchange_app.urls')),
    path('', RedirectView.as_view(url='/mainpage/', permanent=False)),  # 루트 URL 리디렉션
    path('mainpage/', include('mainpage.urls')),  # 메인 페이지를 제공하는 앱의 URL 설정을 포함
    # path('<int:user_pk>/password/', views.change_password, name='change_password')
]

Final_pjt/finlife/urls.py
from django.urls import path
from . import views

app_name = "finlife"
urlpatterns = [
    path('', views.index, name="index"),
    path('filter/', views.filter, name="filter"),
    path('compare/', views.compare_products, name='compare'),
    path('<str:product_type>/<int:product_id>/', views.product_detail, name='product_detail'),
    path('enroll/<str:product_type>/<int:product_id>/', views.enroll_product, name='enroll_product'),
]

Final_pjt/myapp/urls.py
# myapp/urls.py

from django.urls import path
from . import views

app_name ='myapp'
urlpatterns = [
    path('map/', views.map_view, name='map'),  # 빈 문자열로 설정하여 기본 경로로 매핑
]

Final_pjt/survey/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView
from django.views.generic import TemplateView

app_name ='survey'
urlpatterns = [
    path('', views.index, name='index'),
    path('recommendations/', views.recommend_products, name='recommendations'),
]

Final_pjt/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>

  {% load static %}
  <link rel="stylesheet" href="{% static 'nav_base.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"> <!-- Font Awesome 아이콘 -->
  {% comment %} <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> {% endcomment %}
  {% block style %}

  {% endblock style %}
</head>

<body>
    <div class="area"></div>
    <div>
    <nav class="main-menu">
        <ul>
            <li>
                <a href="{% url 'mainpage:mainpage' %}">
                    <i class="fa fa-home fa-2x"></i>
                    <span class="nav-text">
                        MONIMATE 메인페이지
                    </span>
                </a>
            </li>
            <li class="li" class="has-subnav">
                <a href="{% url 'exchange_app:home' %}">
                    <i class="fa fa-dollar-sign fa-2x"></i>
                    <span class="nav-text">
                        환율계산기
                    </span>
                </a>
            </li>
            <li class="li" class="has-subnav">
                <a href="#">
                    <i class="fa fa-bullhorn fa-2x"></i>
                    <span class="nav-text">
                        공지사항
                    </span>
                </a>
            </li>
            <li class="li" class="has-subnav">
                <a href="{% url 'articles:index' %}">
                    <i class="fa fa-comments fa-2x"></i>
                    <span class="nav-text">
                        게시판
                    </span>
                </a>
            </li>

            <li class="li">
                <a href="{% url 'finlife:index' %}">
                    <i class="fa fa-chart-bar fa-2x"></i>
                    <span class="nav-text">
                        금융 상품 비교
                    </span>
                </a>
            </li>
            <li class="li">
                <a href="{% url 'myapp:map' %}">
                    <i class="fa fa-map-marker-alt fa-2x"></i>
                    <span class="nav-text">
                        가까운 은행 찾기
                    </span>
                </a>
            </li>
            <li class="li">
                <a href="{% url 'survey:recommendations' %}">
                    <i class="fa fa-robot fa-2x"></i>
                    <span class="nav-text">
                        AI 상품 추천
                    </span>
                </a>
            </li>
            <li class="li">
                <a href="{% url 'survey:index' %}">
                    <i class="fa fa-chart-pie fa-2x"></i>
                    <span class="nav-text">
                        투자 성향 설문 조사
                    </span>
                </a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="li">
                <a href="{% url "accounts:profile" user.username %}">
                    <i class="fa fa-user fa-2x"></i>
                    <span class="nav-text">
                        프로필 페이지
                    </span>
                </a>
            </li>
            {% endif %}
        </ul>

        <ul class="logout">
            {% if not request.user.is_authenticated %}
            <li>
            <a href="{% url 'accounts:signup' %}">
                <i class="fa fa-user-plus fa-2x"></i>
                    <span class="nav-text">
                        회원가입
                    </span>
                </a>
            </li>  
            <li>
                <a href="{% url 'accounts:login' %}">
                    <i class="fa fa-sign-in-alt fa-2x"></i>
                    <span class="nav-text">
                        로그인
                    </span>
                </a>
            </li>
            {% else %}  
            <li>
                <a href="{% url 'accounts:logout' %}">
                    <i class="fa fa-sign-out-alt fa-2x"></i>
                    <span class="nav-text">
                        로그아웃
                    </span>
                </a>
            </li>
            {% endif %}  
        </ul>
    </nav>
  </div>
  <div class="wrap">
    {% block content %}
    {% endblock content %}
  </div>
</body>
</html>

Final_pjt/templates/basefin.html
{% extends "base.html" %}

{% block style %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
{% endblock style %}

{% block content %}
<h1>검색하기</h1>
<p>검색 조건을 입력하세요</p>
{% block search_form %}{% endblock search_form %}
{% endblock content %}